title = "TOML Example"

[owner]
name = "WeepingDogel"
version = "1.0.0"
sign = '''
╭━━━━┳━━━┳━━━┳━━━━╮
┃╭╮╭╮┃╭━━┫╭━╮┃╭╮╭╮┃
╰╯┃┃╰┫╰━━┫╰━━╋╯┃┃╰╯
╱╱┃┃╱┃╭━━┻━━╮┃╱┃┃
╱╱┃┃╱┃╰━━┫╰━╯┃╱┃┃
╱╱╰╯╱╰━━━┻━━━╯╱╰╯

BY WeepingDogel
'''
showsign = true
	[owner.test]
	number = 1234
